import PDFDocument from 'pdfkit';
import fs from 'fs';

/**
 * 生成PDF文件
 */
export async function generatePdf(data: any, filePath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const stream = fs.createWriteStream(filePath);
    
    doc.pipe(stream);
    
    // 添加标题
    doc.fontSize(20).text('Virtual Diary Export', { align: 'center' });
    doc.moveDown();
    
    // 添加日期
    doc.fontSize(12).text(`Exported on: ${new Date().toLocaleString()}`, { align: 'right' });
    doc.moveDown(2);
    
    // 添加数据部分
    for (const [section, items] of Object.entries(data)) {
      doc.fontSize(16).text(section.toUpperCase(), { underline: true });
      doc.moveDown();
      
      if (Array.isArray(items) && items.length > 0) {
        items.forEach((item: any, index: number) => {

          
          // 格式化不同数据类型的显示
          if (section === 'diaries') {
            doc.text(`  Title: ${item.title}`);
            doc.text(`  Content: ${item.content.substring(0, 100)}...`);
            doc.text(`  Emotions: ${item.emotions.join(', ')}`);
            doc.text(`  Topics: ${item.topics.join(', ')}`);
            doc.text(`  Visibility: ${item.visibility}`);
            doc.text(`  Word Count: ${item.metadata?.wordCount || 'N/A'}`);
          } else if (section === 'feedback') {
            doc.text(`  Type: ${item.type}`);
            doc.text(`  Style: ${item.style}`);
            doc.text(`  Content: ${item.content.substring(0, 100)}...`);
            
            if (item.rating) {
              doc.text(`  Rating: ${item.rating.score}/5`);
              doc.text(`  Feedback: ${item.rating.feedback?.substring(0, 50) || 'None'}...`);
            }
            
            if (item.conversations && item.conversations.length > 0) {
              doc.text(`  Conversations: ${item.conversations.length} messages`);
            }
          } else if (section === 'analytics') {
            doc.text(`  Type: ${item.type}`);
            if (item.range) doc.text(`  Range: ${item.range}`);
            
            // 简化显示分析结果
            const resultStr = JSON.stringify(item.result);
            doc.text(`  Result: ${resultStr.substring(0, 100)}...`);
          }
          
          doc.text(`  Created At: ${item.createdAt}`);
          doc.moveDown();
        });
      } else {
        doc.text('No data available');
      }
      
      doc.moveDown(2);
    }
    
    // 添加页脚
    doc.fontSize(10);
    doc.text('Generated by Virtual Diary - Your personal time travel companion', {
      align: 'center'
    });
    
    doc.end();
    
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });
}

