import PDFDocument from 'pdfkit';
import fs from 'fs';

/**
 * 生成PDF文件
 */
export async function generatePdf(data: any, filePath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const stream = fs.createWriteStream(filePath);
    
    doc.pipe(stream);
    
    // 添加标题
    doc.fontSize(20).text('Virtual Diary Export', { align: 'center' });
    doc.moveDown();
    
    // 添加日期
    doc.fontSize(12).text(`Exported on: ${new Date().toLocaleString()}`, { align: 'right' });
    doc.moveDown(2);
    
    // 添加数据部分
    for (const [section, items] of Object.entries(data)) {
      doc.fontSize(16).text(section.toUpperCase(), { underline: true });
      doc.moveDown();
      
      if (Array.isArray(items) && items.length > 0) {
        items.forEach((item: any, index: number) => {
          doc.fontSize(12).text(`${index + 1}. ${item.title || `Item ${index + 1}`}`);
          doc.fontSize(10);
          
          Object.entries(item).forEach(([key, value]) => {
            if (key === 'title') return;
            
            let valStr = typeof value === 'string' ? value : JSON.stringify(value);
            if (valStr.length > 100) {
              valStr = valStr.substring(0, 100) + '...';
            }
            
            doc.text(`  ${key}: ${valStr}`);
          });
          
          doc.moveDown();
        });
      } else {
        doc.text('No data available');
      }
      
      doc.moveDown(2);
    }
    
    // 添加页脚
    doc.fontSize(10); // 先设置字体大小
    doc.text('Generated by Virtual Diary - Your personal time travel companion', {
      align: 'center'
    });
    
    doc.end();
    
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });
}